### ISSUE TITLE
Publish a changelog

### ISSUE THREAD

**Issue by konklone** [digital-analytics-program/gov-wide-code#17]
There's only so much outsiders can divine by [reading a giant diff](https://github.com/GSA/DAP-Gov-wide-GA-Code/commit/d3c6fe5a67b48d8f1315d2b98b6c8af9e5fe5362). :smiley_cat:

A changelog, written in human prose, of what changed from version to version would be an extremely helpful piece of documentation and future reference for the DAP.

**Comment by gbinal** [comment]
+:100:

**Comment by smarina04** [comment]
@konklone I thought I provided you with a changelog file some time ago?

**Comment by konklone** [comment]
This got started with #23.
