### ISSUE TITLE
Automate the publication of participating domains

### ISSUE THREAD

**Issue by konklone** [digital-analytics-program/gov-wide-code#25]
The DAP currently publishes a list of [~3800 participating websites](https://analytics.usa.gov/data/sites.csv). This has not been updated in some time, and as a dataset that the public and other GSA teams are coming to rely on, it should be updated on a regular schedule.

One way to do this is to task the server running `analytics-reporter` and powering `analytics.usa.gov` with this task. The CSV is currently already stored in the same S3 bucket, and the data should be gettable programmatically from the Google Analytics API. It could be updated nightly and automatically.

**Comment by smarina04** [comment]
Great idea. This will also help tremendously with other internal reporting needs.

**Comment by tdlowden** [comment]
@konklone ... we've satisfied this, no? Ready for close?

**Comment by konklone** [comment]
We did this for second-level's, which is the list of ~3-400. When the bulk data is expanded, as we plan to do this month, it will organically accomplish this task as well, which is to automate the publication of the ~3,800 (more now) and remove manual labor on the part of the DAP.
