### ISSUE TITLE
add tests

### ISSUE THREAD

**Issue by afeld** [digital-analytics-program/gov-wide-code#29]
I want to look into doing some refactoring...want to make sure I don't break it!

**Comment by tdlowden** [comment]
Hey @afeld, we are finally getting around to trying to add these in. Can you expand on this any more? Are there some specific areas you feel would be good for tests? How many do you think we'd need to add in for this length of code?

**Comment by afeld** [comment]
Great! I would think about it in terms of functions, code paths, and coverage. 

Functions: most functions should have at least a couple tests - one for the “base case”, and others to catch edge cases. For example, `_isValidUANum()`. This function is relatively easy to write a test for, because it is idempotent (giving the same input will always result in the same output). You can have one test with a known-good UA number, and others that throw in junk like an empty string, missing the part before the first hyphen, etc. 

Code paths: For any functions that have branching (`if` statements), you’ll want to make sure you have tests that “exercise” (go down) each of these “code paths”. The easiest way to check this is through...

Coverage: Tools like [blanket.js](http://blanketjs.org/) will show which lines of code are hit by tests, and which aren’t. You’ll want to aim for 100% coverage, though it’s rare that projects ever get all the way there. 

All of this being said, some tests are better than no tests, and more tests are easier to write when you have some tests. Hope that helps!
