### ISSUE TITLE
Produce a minification map file

### ISSUE THREAD

**Issue by konklone** [digital-analytics-program/gov-wide-code#31]
Source maps (generally `nameofscript.min.js.map`) are a standard that allow browsers to "unminify" the code for debugging in browser. 

http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/

The map file is only downloaded upon developer action -- in Chrome's case, opening the developer console -- and so the map file is not routinely downloaded and shouldn't meaningfully increase costs. It will meaningfully increase the ability of the DAP team and its IT support staff to identify and solve problems that implementing agencies are experiencing.

A good minification toolset should be able to produce an accompanying source map file, which could then be referenced in the minified JavaScript and hosted next to it on `dap.digitalgov.gov`.

**Comment by tdlowden** [comment]
FYI, this is in progress

**Comment by esabol** [comment]
Using the latest version of Safari, the Web Console shows:

Failed to load resource: the server responded with a status of 403 () https://dap.digitalgov.gov/Federated.js.map

I think this is related?

**Comment by euro** [comment]
Please configure web server to allow http access to *.map file

**Comment by konklone** [comment]
> FYI, this is in progress

@tdlowden Did this ever get done? (I don't see it in the repo, so I'm guessing not.)

**Comment by smarina04** [comment]
source map is added.
