### ISSUE TITLE
YouTube event functions are defined and callable when they shouldn't be

### ISSUE THREAD

**Issue by konklone** [digital-analytics-program/gov-wide-code#32]
Right now [on GSA](http://www.gsa.gov/portal/category/100000) the DAP code throws this error:

![image](https://cloud.githubusercontent.com/assets/4592/9687185/f76f6bee-52f5-11e5-9086-705f324732fb.png)

It means that the `onYouTubePlayerAPIReady` function is getting called. `onYouTubePlayerAPIReady` is a magic function name that the YouTube API may trigger in response to events.

GSA is not enabling YouTube event tracking, which means that `videoArray_fed` is not getting defined on [line 694](https://github.com/digital-analytics-program/gov-wide-code/blob/master/Universal-Federated-Analytics.js#L694) as expected, which causes the error above. 

However, DAP's `onYouTubePlayerAPIReady` function is still getting defined, and so is in the global namespace. This means it can be called when no other DAP YouTube information is uninitialized. But more importantly, it also means that it could overwrite other competing scripts' `onYouTubePlayerAPIReady` function and disrupt site behavior.

This is happening because `onYouTubePlayerAPIReady` is defined inside of an `if` conditional statement. However, functions defined using the form `function nameOfFunction()` inside of a conditional block in JavaScript are always defined, even if the conditional block is never executed. 

![image](https://cloud.githubusercontent.com/assets/4592/9687313/bf1063ba-52f6-11e5-8ce7-af677c1f9806.png)

There are better ways of compartmentalizing these functions so that they do not enter the global namespace. However, a quick way to fix this issue is to define the functions by assigning them to a variable:

![image](https://cloud.githubusercontent.com/assets/4592/9687304/b4eb2668-52f6-11e5-9604-17955320c4fa.png)

The DAP code, overall, should avoid entering any functions into the global namespace unless this is absolutely required. In the case of `onYouTubePlayerAPIReady`, it _is_ required (which is an outdated practice of the YouTube API that gives us no choice), but its definition should be made properly conditional using the method above.

**Comment by ArielZamparini-REISys** [comment]
Having the same problem, not only is the Youtube api out of date with the latest google api release but as mentioned the function `onYouTubePlayerAPIReady` needs an additional `if YOUTUBE` which would completely skip youtube tracking code if that option is not set.

**Comment by tdlowden** [comment]
Marked for review with v3.1

**Comment by tdlowden** [comment]
Remedied (awhile ago). Apologies for not closing earlier!
