### ISSUE TITLE
Expand download tracking extensions lists to track .json

### ISSUE THREAD

**Issue by konklone** [digital-analytics-program/gov-wide-code#34]
This would catch download links for analytics.usa.gov, as well as other sites which link to JSON files, like https://www.opm.gov/our-inspector-general/reports/.

That said, .json files are expected to mostly be used by scripts, not by humans clicking through (unlike CSVs, for example), so it doesn't sound like a huge deal either way.

**Comment by smarina04** [comment]
@konklone this is 8 years old, but better late than never. Do you still believe DAP should track .json as an extension for downloads?
