### ISSUE TITLE
Track protocol of the URL being logged

### ISSUE THREAD

**Issue by konklone** [digital-analytics-program/gov-wide-code#35]
Google Analytics tracks `hostname` by default (e.g. `nasa.gov`) but does not track protocol/scheme (e.g. `http` or `https`). The DAP could set a custom variable for this value and report it as part of each hit.

**Comment by konklone** [comment]
I continue to think this is an easy win. :)

**Comment by konklone** [comment]
I continue to continue to think this is an easy win. :smiley_cat:

**Comment by tdlowden** [comment]
Noted @konklone. I definitely agree on the value. We're going to get this in an upcoming version

**Comment by tdlowden** [comment]
This is available as of v4.0 with custom dim: `URL Protocol`.
