### ISSUE TITLE
Turn on OCSP stapling for dap.digitalgov.gov

### ISSUE THREAD

**Issue by konklone** [digital-analytics-program/gov-wide-code#38]
Without [OCSP stapling](https://sslmate.com/blog/post/ocsp_stapling_in_apache_and_nginx), visitors to DAP-enabled sites that are using OCSP-supporting browsers (at least Firefox and IE, not Chrome) will all ping Symantec to check to see if dap.digitalgov.gov's certificate is revoked. This shares large-scale user browsing behavior with Symantec, not a desired privacy outcome of the DAP.

Enabling OCSP stapling means that revocation information will be included ("stapled") in the initial HTTPS connection that browsers make to dap.digitalgov.gov, so that browsers don't need to make an additional connection to the CA to get this information. This also has the effect of transferring that information over HTTPS (the original connection) rather than HTTP (which OCSP connections generally use).

**Comment by konklone** [comment]
Has this been raised with Akamai or others?

**Comment by tdlowden** [comment]
Thanks for resurfacing. I'm looking into it now.

**Comment by konklone** [comment]
This is resolved now that we've moved to CloudFront. You can see this here:

https://www.ssllabs.com/ssltest/analyze.html?d=dap.digitalgov.gov&s=13.35.121.31&latest
