### ISSUE TITLE
Load with async

### ISSUE THREAD

**Issue by joewiz** [digital-analytics-program/gov-wide-code#41]
DAP's recommended `script` tag lacks an `async` attribute:

```
<!-- We participate in the US government's analytics program. See the data at analytics.usa.gov. -->
<script language="javascript" src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=AGENCY" id="_fed_an_ua_tag"></script>
```

Is it acceptable to add this attribute? The purpose is to eliminate the hit to page load times on our site due to blocking during DNS load time.  DNS lookup times for dap.digitalgov.gov are typically 30ms but we've seen them regularly hit 100ms, even 200ms.

**Comment by tdlowden** [comment]
Hi @joewiz! Thanks for bringing this to our attention. We're currently working on a new code version and when we release it, we'll be changing the documentation to suggest adding the `async` attribute.

**Comment by line-o** [comment]
Does this mean we can use it already and the documentation is not up to date or should we wait for the new code version?

**Comment by joewiz** [comment]
@tdlowden Thanks for your response. Could you confirm that it's safe to use `async` on the current version?

**Comment by SamBronson** [comment]
Sorry to speak out of turn, but if you are using a tag management system, like GTM, the async attribute is not necessary.

**Comment by tdlowden** [comment]
I am under the impression that our current code doesn't yet support `async`, but I'm double checking now.

**Comment by tdlowden** [comment]
@joewiz @line-o confirmed that the current version does not support the `async` attribute. But within a few weeks, the v3.0 code should be available, which will load asynchronously the the `async` attribute.

**Comment by line-o** [comment]
@tdlowden OK, thank you very much.

**Comment by joewiz** [comment]
@tdlowden Yes, thank you!

**Comment by konklone** [comment]
There's an open issue (well, PR) with some discussion of this exact issue: https://github.com/digital-analytics-program/gov-wide-code/pull/28

**Comment by tdlowden** [comment]
This option now available in v3.1! Closing... finally.

**Comment by joewiz** [comment]
Great news! We'll put it to use. Thanks for this improvement and for letting us know.

**Comment by tdlowden** [comment]
Thanks for bringing it to our attention! Sorry it took so long to get this version out.
