### ISSUE TITLE
Link autotracker doesn't work for dynamically generated content

### ISSUE THREAD

**Issue by toolness** [digital-analytics-program/gov-wide-code#45]
It looks like DAP's `_initAutoTracker()` function is called on page ready (or when DAP is asynchronously loaded). Because this function works by finding every `<a>` on the page and adding a `mousedown` handler to it, any `<a>`'s created after this process won't be tracked. This is unfortunate for sites that generate any dynamic content (in our case, [calc.gsa.gov](https://calc.gsa.gov), which loads search results via Ajax).

I can think of a few possible solutions here:
1. Instead of adding an individual event handler to every link, add a single event handler to `<html>` that dynamically examines `event.target` and, if it's an `<a>` with an appropriate `href` attribute, tracks the action. This is a non-trivial change to how DAP auto-tracks links, but it doesn't require any changes to client code, and I don't _think_ it would affect performance.
2.  ~~Minorly refactor the DAP script so that it exposes a `DAP_autoTrackLinks()` function which client pages can pass an array of links into; DAP then attaches its auto-tracking handlers as needed.~~ Tell clients to call `_initAutoTracker()` whenever they add new links to the page. This is the strategy recommended by E-Nor, the creator of the DAP script. This requires client code to do some manual work if it wants to track dynamically-generated links, and it also requires us to document the API and support it going forward (which I started in #47).
   
   However, this solution currently suffers from some flaws mentioned in https://github.com/digital-analytics-program/gov-wide-code/pull/47#issuecomment-253232382. A workaround might be to change `_initAutoTracker()` to take an optional array or `NodeList` of links--defaulting to all links on the page if none is provided.

**Comment by tdlowden** [comment]
Hey Atul, thanks for this notification. We've seen this happen before for pages with dynamically loaded content. What we've done previously is ask the site owners to re-run the `initAutoTracker()` after the content (in this case, the links) is loaded. I'm going to look back and see if I can find some documentation on those past issues. That said, your suggestions interest me and I'll definitely pass them on to our dev team.
