### ISSUE TITLE
Link autotracker doesn't account for keyboard users

### ISSUE THREAD

**Issue by toolness** [digital-analytics-program/gov-wide-code#46]
It looks like the auto-tracking code (specifically `_tagClicks()`) is binding event handlers to `mousedown`, and as a result, it won't track the activity of [keyboard users](http://webaim.org/techniques/keyboard/) who press <kbd>Enter</kbd> to activate links.

I'm not sure if this is a big deal or not, but I figured I'd mention it.

I think it could probably be fixed by binding to `keydown` in `_tagClicks()` and filtering based on whether <kbd>Enter</kbd> was pressed.

**Comment by tdlowden** [comment]
This is a fantastic catch! Thank you. Passing on for our 3.2 version feature updates.

**Comment by tdlowden** [comment]
We added this to our 4.0 code and we're demoing it on a webinar Wednesday!
