### ISSUE TITLE
Invalid parameter set: DOUNBLECLICK_LINK: false

### ISSUE THREAD

**Issue by laurenancona** [digital-analytics-program/gov-wide-code#54]
Minor typo: [parameter name](https://github.com/digital-analytics-program/gov-wide-code/blob/master/Universal-Federated-Analytics.js#L52) should be `DOUBLECLICK_LINK`.

I'm unsure what other side effects this may have on tracking without more testing, but it should probably be updated in both versions of the hosted script as soon as is reasonable.

/cc @tdlowden

**Comment by laurenancona** [comment]
Update: this is apparently an intentional misspelling to avoid JS collisions in implementations where another GA Profile is present.
Noting my opinion that this is a hacky workaround and closing.

**Comment by konklone** [comment]
It's a bad enough hacky workaround that IMO it should remain open, and e-NOR should be asked to reimplement this with proper namespacing. It will cause people to make mistakes that will be very difficult to track down.

But if the team closes it, I won't re-re-open it. :)

**Comment by tdlowden** [comment]
This was remedied. Moving to close.
