### ISSUE TITLE
Angular 2 - Virtual page view tracking

### ISSUE THREAD

**Issue by skolli853780** [digital-analytics-program/gov-wide-code#59]
Hello,

We are using Digital analytics-program in our application, it works well for individual pages.. since our application is developed using Angular 2, we do not reload the whole page when a button is clicked.. I have looked at the documentation about Virtual pageview tracking.. one of the parameters gas function takes is url.. we use angular Routerlink to navigate between pages.. Is there a way we can pass Routerlink instead of URL? please advise

Thanks 
SK

**Comment by tdlowden** [comment]
Hi. Single-page app libraries like Angular and React do pose some problems for pageview tracking. I'm not familiar with Routerlink, but I have seen some folks use Angulartics to help with virtual pageviews. Alternatively, you can send virtual pageviews with a gas function by coding it yourself. Documentation can be found on [page 14 of our Code Capabilities Summary](https://s3.amazonaws.com/sitesusa/wp-content/uploads/sites/212/2014/05/DAP_v3.1_CodeSummary_Aug2016-1-1.pdf)

**Comment by skolli853780** [comment]
Can we use Angulartics along with your program? we have been asked to use DAP for Google analytics

**Comment by tdlowden** [comment]
You can. You just need to configure it to send the pageviews to the DAP UA ID. :)

**Comment by skolli853780** [comment]
how is your program different from Google analytics code..

  <script defer>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
    ga('create', '<%= GOOGLE_ANALYTICS_ID %>', 'auto');
    ga('send', 'pageview');
  </script>

can I replace https://www.google-analytics.com/analytics.js with DAP js file? please advise.. I tried Angulartics, there is some issue with our version of Angular..

**Comment by tdlowden** [comment]
Please read the [instructions in the README](https://github.com/digital-analytics-program/gov-wide-code#participating-in-the-dap). You don't use normal GA block to run DAP, you use our own custom `<script>` that calls our code either locally or from our central location.
