### ISSUE TITLE
Enable content-encoding (gzip/brotli) for JS files

### ISSUE THREAD

**Issue by mattbrundage** [digital-analytics-program/gov-wide-code#62]
The DAP GA JavaScript files served from https://dap.digitalgov.gov/ are currently being served uncompressed. Turning on gzip or brotli would be a quick win.

Further info: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding

**Comment by konklone** [comment]
:+1: Yes, this should be an easy win.

**Comment by konklone** [comment]
Note it's only 20K, but yeah, Google's pagespeed scanner suggests that gzip would reduce the size by 74%, down to ~5K.

**Comment by tdlowden** [comment]
Thanks for this!

**Comment by mattbrundage** [comment]
DAP is now gzipping the minified file. Thanks for that.
Looks like this fix is documented in commit 8e4e5965145dbbfd3c1fef4bf91cb0f16c9aec3a
