### ISSUE TITLE
Organize as a npm package

### ISSUE THREAD

**Issue by hsiaoyi0504** [digital-analytics-program/gov-wide-code#65]
It would be good to make this as a npm package and can be installed by **npm**. This change will let user don't need to include a copy into their repo.

**Comment by tdlowden** [comment]
hi! can you elaborate? are you referring to the https://github.com/18F/analytics.usa.gov/ repo?

**Comment by tdlowden** [comment]
Or do you mean for DAP <script> implementation?

**Comment by hsiaoyi0504** [comment]
Hi @tdlowden, I think the suggestion (feature request) is for this repo.
Make this repo as a **npm** package enable users (built project based on it) to install the script through `npm install` and keep track the version of it through **package.json** https://docs.npmjs.com/files/package.json.

**Comment by hsiaoyi0504** [comment]
For example, we have a project use the **Universal-Federated-Analytics.js**, but we will combine this file together with other **.js** files, and basically, we don't modify the original script so we don't have a copy inside the repo, but collecting this script during building our project.

**Comment by eddietejeda** [comment]
We've begun taken the steps to turn this into npm package in this pull request: https://github.com/digital-analytics-program/gov-wide-code/pull/68

I think a few other clean up steps are required, but afterward, we can see if we can publish to npm.

**Comment by hsiaoyi0504** [comment]
@eddietejeda Thanks for the information. BTW, `npm` can install package just on a branch https://stackoverflow.com/questions/39732397/install-specific-branch-from-github-using-npm.
