### ISSUE TITLE
Store the DAP snippet URL as some kind of custom variable

### ISSUE THREAD

**Issue by konklone** [digital-analytics-program/gov-wide-code#7]
The DAP JS should track which URL was used to load the DAP JS. This will make it possible to track more precisely how agencies are currently referencing the DAP.

**Comment by tdlowden** [comment]
We will be able to do this because the switch from Classic to UA changes "custom variables" to "custom dimensions" and the GUI reporting will reflect this. So if we run reports for custom variables, we'll be able to identify the sites that have yet to implement.

**Comment by konklone** [comment]
That wasn't my request - I was saying that tracking the exact URL will tell the DAP *how* an agency is implementing the DAP, by showing where their file is hosted for any given domain.

**Comment by tdlowden** [comment]
Ah, apologies Eric. I misunderstood.

**Comment by tdlowden** [comment]
On wish list for v3.2

**Comment by konklone** [comment]
:pray:

**Comment by konklone** [comment]
@tdlowden This is done now, right?

**Comment by tdlowden** [comment]
This is done, as of v4.0. Apologies for not closing awhile ago.
