### ISSUE TITLE
Script Conflict with Mediaelements

### ISSUE THREAD

**Issue by stphnwlkr** [digital-analytics-program/gov-wide-code#72]
We attempted to add yt=true to our script DAP call ("&amp;yt=true") and it is causing a conflict with the mediaelements.js script. Right now the mediaelements is not used everywhere so we are wondering if there is a way to programmaticly append "yt=true" to the DAP script.  Something like

<script>
ga(some code 'yt=true').append;
</script>

**Comment by tdlowden** [comment]
Thanks for raising the issue, @stphnwlkr. Passing this issue to the dev team now.

**Comment by tdlowden** [comment]
@stphnwlkr, can you provide a URL where mediaelements.js is being used, so we can test?

**Comment by stphnwlkr** [comment]
www.choose.va.gov is one.

**Comment by tdlowden** [comment]
It took us a while, but this is finally addressed:
https://github.com/digital-analytics-program/gov-wide-code/blob/master/documentation/GSA%20DAP%204.1%20-%20Quick%20Guide.pdf

Sorry for the delay!
