### ISSUE TITLE
suggestion: move documentation to HTML

### ISSUE THREAD

**Issue by afeld** [digital-analytics-program/gov-wide-code#81]
Right now, the guide, release notes, etc. are PDFs on GitHub. This leads to a bunch of problems:

- It's split from the documentation that _does_ live on digital.gov
- DAP can't get analytics on its own documentation
- GitHub's embedded PDF viewer doesn't support selecting/copying text or clicking links, meaning the PDF needs to be downloaded and opened in order to copy the `<script>` tags, etc.
- Things like navigation within the documents is harder
- PDFs aren't responsive
- HTML is (arguably) easier to make accessible than PDFs

Moving the documentation to HTML on digital.gov would solve all these issues.

**Comment by afeld** [comment]
Heh, I forgot that the program contains [analytics.usa.gov](https://analytics.usa.gov). No strong feelings about where the content lives, more that it's HTML and in one place.

**Comment by tdlowden** [comment]
We are working on this. Might be HTML in GH in markdown in the short term, but trying to move it to HTML.
