### ISSUE TITLE
gaUri[0] undefined

### ISSUE THREAD

**Issue by ghenle** [digital-analytics-program/gov-wide-code#83]
@line 675

    else if(extDoc.length && arr[i].href.toLowerCase().indexOf("mailto:") !== -1 && arr[i].href.toLowerCase().indexOf("tel:") === -1){
      // Tracking outbound emails
      var gaUri = arr[i].href.match(/[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}/i);
      _tagClicks(arr[i],'Outbound MailTo', gaUri[0], '', 0);
    }

If regex href.match doesn't find a match it will return and set gaUri to NULL. gaUri[0] will trigger an error.

**Comment by smarina04** [comment]
@ghenle We are looking into this as part of the next code release.

**Comment by smarina04** [comment]
This is fixed.
